//ADDING PRODUCTS FROM PAGES
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

//INSIDE_CART
export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

//CHECK_OUT
////AUTHENTICATION
/////SIGNUP
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const RESET_STATE_AFTER_SIGNUP_SUCCESS =
  "RESET_STATE_AFTER_SIGNUP_SUCCESS";
///SIGN_IN
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
///SIGN_OUT
export const SIGNOUT_START = "SIGNOUT_START";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAIL = "SIGNOUT_FAIL";

///PAYMENT_WITH_CARD
export const PAYMENT_START = "PAYMENT_START";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";
//FETCH_CUSTOMER_DATA
